### ISSUE TITLE
Design Docs Checklist

### ISSUE THREAD

**Issue by taylormusolf** [elliotkuok/readytable#1]
# Wiki Home Page
- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [x] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [x] Correctly formatted
  - [x] each wiki page is listed in bullet points
  - [x] all links route the correct page
## Comments
---
# Feature List
- [x] Should have 7 Features.
  - [x] 3 of those are User Auth, Hosting and Production README.
  - [x] The other 4 are unique to this project
- [x] Contains a description sentence of the app
- [x] Includes two to three detailed bullets on functionality and presentation of feature
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each Feature
- [x] Correctly formatted
  - [x] Features are listed in an ordered list
  - [x] Each Feature is broken down into bullet points
## Comments
- Responding to your comment on 'New account creation', you wouldn't want the user to be able to make reservations if not logged in if you are planning on tying the reservation to a `user_id` (which you are).
- We will want delete for reviews so it can be a full CRUD feature even if OpenTable doesn't do it.
- The search feature is a little light as is so you should have your Map bonus as part of Search.
---
# Database Schema
- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
  - [x] primary key
  - [x] not null
  - [x] unique
  - [x] indexed
  - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
 - [x] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [x] Correctly formatted
  - [x] schema is written in a table format
  - [x] the table's name are lowercased, snake_cased and `back_ticked`
  - [x] the table header column names are bolded
  - [x] columns names are lowercased and snaked_cased and `back_ticked`
## Comments
- For `restaurants` I think all of the associations should be fine.  For indices think about any field you would want to search for in the table.  If you want to search by it then it should have an index.
- For `reservations` does OpenTable ask for `first_name` and `last_name` on the reservation?  You should be able to get that info from the `users` table.  Would you want to put a unique: true on `[user_id, restaurant_id]`?  That would mean that the user could only have a reservation at this restaurant once ever.
- For `reviews` is the `overall_rating` an average of the other ratings or is it its own rating? 
---
# Sample State
- [x] State shape is flat!
- [x] State's keys are camelCased
- [x] All keys within the values in the state are accessible in the schema
- [x] Correctly formatted
  - [x] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
  - [x] Top level slices
    - [x] `entities`
    - [x] `session`
    - [x] `errors` (here or in `ui`)
    - [x] `ui` (if needed)
  - [x] Should NOT have nested slices, aka `comments` inside of `posts`
   + Some info from other tables is ok, for instance:
    + the author username and imageurl for a post. basically any info that the user can't change
    + like count and a boolean on whether the user likes the post instead of a likes slice
## Comments
---
# Backend Routes
- [x] Contains the following sections: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Routes does not contain superfluous routes
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
  + probably doesn't need a `GET likes` api endpoint because that info comes through the post show
## Comments
---
# Frontend Routes
- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Correctly formatted
  - [x] Routes are displayed with `inline coding text` (backticks)
## Comments

**Comment by taylormusolf** [comment]
@elliotkuok Took a look at the docs you had.  Looks like you have more to do on your Feature List.  Let me know when you have made some updates and I can take another look.

**Comment by taylormusolf** [comment]
@elliotkuok Just reviewed your Features and Schema docs.  Left you some feedback.  Let me know if you have any questions or make any updates.
